#  Q2-Clustering-40%

In [1]:
# Libraries
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import mutual_info_classif
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score, recall_score, f1_score
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

#Import some libraries to make displaying easier
import warnings
warnings.filterwarnings('ignore')

pd.get_option("display.max_columns")

20

## a. (10 pts) Load and use the above data set, but do not use the class labels

In [5]:
# Read the CSV file from the URL
df = pd.read_csv('wine-quality.csv', sep=";")

# Drop rows with missing values
df = df.dropna()

# Drop duplicates
df = df.drop_duplicates()

# Split the data into input and target / Discard the class labels
X = df.drop("quality", axis=1)

X

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8
5,7.4,0.660,0.00,1.8,0.075,13.0,40.0,0.99780,3.51,0.56,9.4
...,...,...,...,...,...,...,...,...,...,...,...
1593,6.8,0.620,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0

## b. (10 pts) Apply the k-Means clustering algorithm; experiment with a different number of cluster
centres and discover the best inertia and silhouette values that you can get.

c. (10 pts) Print the clustering results with your code: number of data items per cluster, quality of
clustering measured by the inertia and silhouette values for the best parameters for k-means

In [3]:
# Experiment with different numbers of clusters to find the best inertia and silhouette scores
best_inertia = None
best_silhouette = None
best_clusters = None

for n_clusters in range(2, 11):
    kmeans = KMeans(n_clusters=n_clusters, random_state=42)
    kmeans.fit(X)
    inertia = kmeans.inertia_
    silhouette = silhouette_score(X, kmeans.labels_)
    cluster_counts2 = pd.Series(best_clusters).value_counts()
    print(f"Number of data items per cluster: {cluster_counts2.to_dict()}")
    print(f"k={n_clusters}, inertia={inertia:.2f}, silhouette={silhouette:.2f}")
    if best_inertia is None or inertia < best_inertia:
        best_inertia = inertia
        best_silhouette = silhouette
        best_clusters = kmeans.labels_

# Print the best clustering results
cluster_counts = pd.Series(best_clusters).value_counts()
print(f"Best clustering with k={len(cluster_counts)}, inertia={best_inertia:.2f}, silhouette={best_silhouette:.2f}")
print(f"Number of data items per cluster: {cluster_counts.to_dict()}")

Number of data items per cluster: {}
k=2, inertia=608302.39, silhouette=0.60
Number of data items per cluster: {0: 1002, 1: 357}
k=3, inertia=345843.81, silhouette=0.52
Number of data items per cluster: {2: 677, 1: 472, 0: 210}
k=4, inertia=247780.57, silhouette=0.51
Number of data items per cluster: {1: 648, 2: 437, 0: 209, 3: 65}
k=5, inertia=195629.34, silhouette=0.45
Number of data items per cluster: {0: 532, 3: 364, 1: 244, 2: 159, 4: 60}
k=6, inertia=152400.77, silhouette=0.45
Number of data items per cluster: {0: 532, 2: 364, 1: 244, 4: 153, 3: 64, 5: 2}
k=7, inertia=127616.27, silhouette=0.40
Number of data items per cluster: {0: 341, 3: 319, 6: 278, 1: 204, 4: 151, 2: 64, 5: 2}
k=8, inertia=112409.46, silhouette=0.39
Number of data items per cluster: {5: 345, 2: 322, 0: 269, 7: 184, 4: 118, 1: 78, 6: 41, 3: 2}
k=9, inertia=98395.12, silhouette=0.39
Number of data items per cluster: {4: 336, 0: 314, 5: 258, 1: 114, 6: 111, 2: 110, 7: 71, 3: 43, 8: 2}
k=10, inertia=86577.81, silhouette=0.39
Best clustering with k=10, inertia=86577.81, silhouette=0.39
Number of data items per cluster: {3: 318, 4: 294, 0: 218, 9: 131, 7: 124, 8: 96, 6: 74, 2: 59, 1: 43, 5: 2}

---------